### ISSUE TITLE
Aim 1: Write first draft of discussion for aim 1

### ISSUE THREAD

**Issue by rekkasa** [rekkasa/thesis#7]
### Main findings
- We found systematic separation strategy based on the reference class focused by each method (risk-based, treatment effect modeling, OTR).
- Overview of discussion from original paper.
### Limitations
- no focus on observational research
- Different approach on [Kunzel et al](https://www.pnas.org/doi/epdf/10.1073/pnas.1804597116)
- ...
### Future research
- ...
## TODO
- Main findings
    - [x]  why is TEM more intuitive?
- Limitations
  - [x] Kunzel
  - [x] only observational data considered
- Future research
  - [x] extend to observational
